# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57d40cde22ddbdb7c72b9d15c0a73cc9bd4e49731b3355fbad0b8ff84e38f923f423d84184b06a8e0a71810cbbcd8fa00b8c178643d09dc6440d7f04089a337c

test:
  secret_key_base: 98c0ab8618e3357919a7c44e600a19d09dcbe751114f28416bd574385c83f30d71336f9124231b36c9d7417524aea4d451646c5d3dd99342e8caad7784c54bbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
